# Part_1 Numpy

In [1]:
import numpy as np

# Task_1

### Create np.array 5 x 2

In [2]:
a = np.arange(10).reshape(5, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### Assign column_1 = [1,2,3,3,1] & column_2 = [6,8,11,10,7]

In [3]:
a[:,0] = [1,2,3,3,1]
a[:,1] = [6,8,11,10,7]
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

### Use mean()

In [4]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

# Task_2

### Subtract array

In [5]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [6]:
a_centered.shape

(5, 2)

# Task_3

In [7]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

### Create a new array from each column in array 'a'

In [8]:
a_1 = a_centered[:,0]
a_2 = a_centered[:,1]

In [9]:
a_1

array([-1.,  0.,  1.,  1., -1.])

In [10]:
a_2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

### Get Scalar value

In [11]:
a_centered_sp = np.dot(a_1, a_2)
a_centered_sp

8.0

### calculate 'N'

In [12]:
rows, columns = a_centered.shape
rows

5

### Division

In [13]:
result = a_centered_sp / (rows - 1)
result

2.0

# Task_4

In [14]:
b = np.cov(a.T)

In [15]:
b[0,1]

2.0

# Part_2 Pandas

In [16]:
import pandas as pd

# Task_1

### Create DataFrame 'authors'

In [17]:
authors = pd.DataFrame({
    'author_id': [1,2,3],
    'author_name': ['Turgenev', 'Chehov', 'Ostrovskiy']
}, columns = ['author_id', 'author_name'])

# Show DataFrame
authors

author_id author_name
0          1    Turgenev
1          2      Chehov
2          3  Ostrovskiy

### Create DataFrame 'books'

In [18]:
books = pd.DataFrame( {
    'author_id': [1,1,1,2,2,3,3],
    'book_title': ['Fathers and Sons', 'Rudin', 'Noble Nest', 'Thick and Thin', 'Lady with a dog ', 'thunderstorm', 'Talents and fans'],
    'price': [450, 300, 350, 500, 450, 370, 290]
}, columns = ['author_id', 'book_title', 'price'] )

# Show DataFrame
books

author_id        book_title  price
0          1  Fathers and Sons    450
1          1             Rudin    300
2          1        Noble Nest    350
3          2    Thick and Thin    500
4          2  Lady with a dog     450
5          3      thunderstorm    370
6          3  Talents and fans    290

# Task_2

In [19]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'outer')
authors_price

author_id author_name        book_title  price
0          1    Turgenev  Fathers and Sons    450
1          1    Turgenev             Rudin    300
2          1    Turgenev        Noble Nest    350
3          2      Chehov    Thick and Thin    500
4          2      Chehov  Lady with a dog     450
5          3  Ostrovskiy      thunderstorm    370
6          3  Ostrovskiy  Talents and fans    290

# Task_3

In [20]:
top5 = authors_price.nlargest( 5, 'price' )
top5

author_id author_name        book_title  price
3          2      Chehov    Thick and Thin    500
0          1    Turgenev  Fathers and Sons    450
4          2      Chehov  Lady with a dog     450
5          3  Ostrovskiy      thunderstorm    370
2          1    Turgenev        Noble Nest    350

In [21]:
top5 = top5.reset_index( drop = True )
top5

author_id author_name        book_title  price
0          2      Chehov    Thick and Thin    500
1          1    Turgenev  Fathers and Sons    450
2          2      Chehov  Lady with a dog     450
3          3  Ostrovskiy      thunderstorm    370
4          1    Turgenev        Noble Nest    350

# Task_4

In [22]:
authors_price

author_id author_name        book_title  price
0          1    Turgenev  Fathers and Sons    450
1          1    Turgenev             Rudin    300
2          1    Turgenev        Noble Nest    350
3          2      Chehov    Thick and Thin    500
4          2      Chehov  Lady with a dog     450
5          3  Ostrovskiy      thunderstorm    370
6          3  Ostrovskiy  Talents and fans    290

In [23]:
max_price = authors_price.groupby( 'author_name' ).agg( { 'price': 'max' } )
max_price.rename({'price': 'max_price'}, inplace=True)
max_price = max_price.reset_index()
max_price['author_id'] = [2,3,1]
max_price.set_index( 'author_id', inplace = True )

max_price

author_name  price
author_id                   
2              Chehov    500
3          Ostrovskiy    370
1            Turgenev    450

In [24]:
min_price = authors_price.groupby( 'author_name' ).agg( { 'price': 'min' } )
min_price.rename(columns = {'price': 'min_price'}, inplace=True)
min_price = min_price.reset_index()
min_price['author_id'] = [2,3,1]
min_price.set_index( 'author_id', inplace = True )

min_price

author_name  min_price
author_id                       
2              Chehov        450
3          Ostrovskiy        290
1            Turgenev        300

In [28]:
mean_price = authors_price.groupby( 'author_name' ).agg( { 'price': 'mean' } )
mean_price.rename(columns = {'price': 'mean_price'}, inplace=True)
mean_price = mean_price.reset_index()
mean_price['author_id'] = [2,3,1]
mean_price.set_index( 'author_id', inplace = True )

mean_price

author_name  mean_price
author_id                        
2              Chehov  475.000000
3          Ostrovskiy  330.000000
1            Turgenev  366.666667

In [42]:
authors_stat = pd.concat( [ min_price, max_price['price'] ], axis = 1 )
authors_stat.rename(columns = {'price': 'max_price'}, inplace=True)
authors_stat

author_name  min_price  max_price
author_id                                  
2              Chehov        450        500
3          Ostrovskiy        290        370
1            Turgenev        300        450

In [43]:
authors_stat = pd.concat( [ authors_stat, mean_price['mean_price'] ], axis = 1 )
authors_stat

author_name  min_price  max_price  mean_price
author_id                                              
2              Chehov        450        500  475.000000
3          Ostrovskiy        290        370  330.000000
1            Turgenev        300        450  366.666667

In [48]:
authors_stat.reset_index(drop = True, inplace = True)
authors_stat

author_name  min_price  max_price  mean_price
0      Chehov        450        500  475.000000
1  Ostrovskiy        290        370  330.000000
2    Turgenev        300        450  366.666667

In [49]:
authors_stat.columns

Index(['author_name', 'min_price', 'max_price', 'mean_price'], dtype='object')